"""
Helper functions for step renderers
"""

from datetime import datetime

def generate_complete_strategy_export(keyword: str, suggestions: dict) -> str:
    """Generate a complete strategy export in markdown format"""
    
    strategy_content = f"""# Content Strategy for "{keyword}"

Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Quick Wins
{suggestions.get("quick_wins", "No quick wins available")}

## Content Ideas  
{suggestions.get("content_ideas", "No content ideas available")}

## Technical SEO
{suggestions.get("technical_seo", "No technical SEO suggestions available")}

## Action Plan

### Immediate Next Steps:

1. **Content Creation Priority:**
   - Start with quick-win content from the Quick Wins section
   - Focus on gaps your competitors haven't filled
   - Create comprehensive guides that outrank existing content

2. **Technical Implementation:**
   - Apply all technical SEO recommendations
   - Ensure mobile-first design and fast loading
   - Implement structured data for featured snippets

3. **Content Distribution:**
   - Repurpose main content into multiple formats (blog, video, infographic)
   - Create supporting content that links back to your main {keyword} page
   - Build topic clusters around {keyword} and related terms

4. **Performance Monitoring:**
   - Track rankings for "{keyword}" and variations
   - Monitor competitor content updates
   - Measure user engagement and conversion rates

---
Generated by AI Keyword Tool
"""
    
    return strategy_content
