name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock
    
    - name: Create test environment file
      run: |
        echo "OPENAI_API_KEY=test-key-for-ci" > .env
    
    - name: Run tests with pytest
      run: |
        python -m pytest test_refactor.py test_services.py test_utils.py -v --tb=short
    
    - name: Test app imports
      run: |
        python -c "import app; print('✅ App imports successfully')"
    
    - name: Check code style (optional)
      run: |
        pip install flake8
        flake8 --max-line-length=100 --ignore=E501,W503 *.py || echo "Style check completed"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run security check
      run: |
        python security_check.py
    
    - name: Check for API key leaks
      run: |
        # Ensure no API keys are committed
        if grep -r "sk-" --exclude-dir=.git --exclude="*.yml" --exclude="*.md" .; then
          echo "❌ Potential API key found in code!"
          exit 1
        else
          echo "✅ No API keys found in code"
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy
    
    - name: Run flake8
      run: |
        flake8 --max-line-length=100 --ignore=E501,W503 *.py || true
    
    - name: Run type checking (optional)
      run: |
        mypy --ignore-missing-imports *.py || echo "Type checking completed"
